backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Site Content"
    files:
      - file: "gallery.json"
        label: "Gallery"
        name: "gallery"
        format: "json"
        fields:
          - label: "Photos"
            name: "items"
            widget: "list"
            summary: "{{fields.alt}} ({{fields.cat}})"
            fields:
              - {label: "Image", name: "src", widget: "image"}
              - {label: "Alt Text", name: "alt", widget: "string"}
              - {label: "Category", name: "cat", widget: "select", options: ["Lighting","Panels","Outdoor","RV/Garage"]}
